version: "3"

services:
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.1.0
    command: --config /oauth2-proxy.cfg
    volumes:
      - "./assets/oauth2-proxy.cfg:/oauth2-proxy.cfg"
    depends_on:
      - redis
      - keycloak
    networks:
      oauth2-proxy: {}
      reverse-proxy: {}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10

  redis:
    image: redis:6.0.10-alpine
    networks:
      oauth2-proxy: {}

  keycloak:
    image: jboss/keycloak:10.0.0
    command:
      [
        '-b',
        '0.0.0.0',
        '-Djboss.socket.binding.port-offset=1000',
        '-Dkeycloak.migration.action=import',
        '-Dkeycloak.migration.provider=dir',
        '-Dkeycloak.migration.dir=/realm-config',
        '-Dkeycloak.migration.strategy=IGNORE_EXISTING',
      ]
    volumes:
      - ./assets/keycloak:/realm-config
    environment:
      KEYCLOAK_USER: admin@example.com
      KEYCLOAK_PASSWORD: password
      TZ: Europe/Berlin
    networks:
      reverse-proxy: {}

  nginx:
    image: nginx:1.19.6-alpine
    volumes:
      - "./assets/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - 80:80/tcp
    networks:
      reverse-proxy:
        aliases:
          - keycloak.opencast.local

networks:
  oauth2-proxy: {}
  reverse-proxy: {}
